In [1]:
import torch

In [2]:
import torchvision

In [3]:
import numpy

In [4]:
test = numpy.array([1,2,3])

In [5]:
test

array([1, 2, 3])

In [7]:
test2 = torch.from_numpy(test)

In [8]:
test2

tensor([1, 2, 3])

In [10]:
um = torch.tensor([1,2,3])

In [11]:
um.size()

torch.Size([3])

In [14]:
um2 = torch.tensor([[1,2],[2,3]])

In [15]:
um2


tensor([[1, 2],
        [2, 3]])

In [17]:
um2.size()

torch.Size([2, 2])

In [18]:
um.log()

RuntimeError: "log" not implemented for 'torch.LongTensor'

In [19]:
um.float().log()

tensor([0.0000, 0.6931, 1.0986])

In [20]:
r3 = torch.rand(4,6)

In [22]:
r3

tensor([[0.3521, 0.5274, 0.7123, 0.0745, 0.6216, 0.9869],
        [0.4215, 0.4698, 0.2014, 0.8004, 0.7848, 0.4098],
        [0.8216, 0.1875, 0.3533, 0.8752, 0.0890, 0.1494],
        [0.3387, 0.8036, 0.7240, 0.2369, 0.4617, 0.3309]])

In [23]:
r3[1,:]

tensor([0.4215, 0.4698, 0.2014, 0.8004, 0.7848, 0.4098])

In [24]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([1,2,3,4])

In [25]:
a*b #component-wise

tensor([ 1,  4,  9, 16])

In [26]:
a+b

tensor([2, 4, 6, 8])

In [27]:
a@b

tensor(30)

In [28]:
1*1 + 2*2 + 3*3 + 4*4

30

In [30]:
x = torch.tensor(1.0, requires_grad = True)
y = torch.tensor(2.0, requires_grad = True)
z = torch.tensor(0.0, requires_grad = True)

In [31]:
a = x+y
b = torch.max(y,z)
f = a*b

In [39]:
f.retain_grad()
f.backward()

In [42]:
print(f.grad)

tensor(1.)


In [43]:
x.grad

tensor(2.)

In [45]:
y.grad

tensor(5.)